### ISSUE TITLE
MODBUS_MAX_READ_COUNT and MODBUS_MAX_WRITE_COUNT are hardcoded

### ISSUE THREAD

**Issue by andruhon** [hirschenberger/modbus-rs#13]
Don't know if it is possible: It would be nice to make them configurable somehow. 

I know that my controller certainly accepts 56 words after the header (7d/125 in total), however MODBUS_MAX_WRITE_COUNT is hardcoded to be 79/121

**Comment by hirschenberger** [comment]
You're right. The [Modbus Standard](http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf) Page 5 defines a max packet size of 260bytes.
I got the number from the [libmodbus](https://github.com/stephane/libmodbus/blob/7e5951675e52847e4f86c6121ccc8c5fa245bfd3/src/modbus.h#L81) implementation. But it is the max number of coils (bits) which can be written, not the packet size.

Thank you for the hint.

**Comment by andruhon** [comment]
I think that we can, at least hardcode the MAX_WRITE according to the standard as 260 and limit the MAX size on the application level if needed (for some controllers MAX size is less than documented 260)

**Comment by andruhon** [comment]
For example my Schneider M258 accepts 129 and choking with anything above.

**Comment by hirschenberger** [comment]
Yes, it's an application level limit. modbus-rs should support the whole range.
Fixed in 4e640e2e54730d69c69a15f4ba7c4728f9da36bf

**Comment by andruhon** [comment]
Cool thanks! By the way you've made a great lib! :+1:
