### ISSUE TITLE
How specify the Unit ID to connect with?

### ISSUE THREAD

**Issue by chespinoza** [hirschenberger/modbus-rs#18]
Hi, thanks for your effort on this lib.

I'm trying to figure out where can be specified the Unit ID in order to select a slave device to connect with.

Cheers!

**Comment by hirschenberger** [comment]
Hello,

it's the field (`uid`) in the `Transport` struct. There's no function to set it explicitly (but there probably should be), the default value is `1`.
You can change it after creating a new `Transport`. 

```rust
let mut t = Transport::new("192.168.1.1").unwrap();
t.uid = 42;
...
```

Greetings, Falco

**Comment by chespinoza** [comment]
Thanks Falco, I really appreciate your quick help.
