### ISSUE TITLE
Remove dependency on "diagslave" in tests

### ISSUE THREAD

**Issue by kinghajj** [hirschenberger/modbus-rs#2]
I tried running "cargo test" on my MacBook, and got an error when a test attempted to run this program, which is for 32-bit Linux systems. I understand it was probably just added for quickness, but portability will be important; having binaries in Git repos is generally bad form; and depending on a non-FOSS program feels "icky" :)

**Comment by hirschenberger** [comment]
Yes your concerns are legitimate. But I'd like to test my Modbus implementation against another, stable implementation. 
Perhaps I'll include a [pymodbus](https://github.com/bashwork/pymodbus) or [libmodbus](https://github.com/stephane/libmodbus) based server, which should be more portable between platforms.

**Comment by hirschenberger** [comment]
Resolved in `0.0.4`.
Can you test if the build works with and without the `modbus-server-tests` feature on your box.
You need `libmodbus` and `pkg-config` for this.

```
cargo test
cargo test --features modbus-server-tests
```

**Comment by kinghajj** [comment]
Both of these work just fine on my laptop! Thanks a bunch.
