### ISSUE TITLE
Server implementation?

### ISSUE THREAD

**Issue by kinghajj** [hirschenberger/modbus-rs#20]
How difficult do would it be to extend this to support creating Modbus servers/slaves?

**Comment by hirschenberger** [comment]
I've not looked into it in detail, but it should not be too hard. Perhaps [libmodbus](https://github.com/stephane/libmodbus) can be used as inspiration.
The difference (beside the establishment of the connection) is, that a mapping to the state memory must be created. In `libmodbus` this is done by creating [mappings](https://github.com/stephane/libmodbus/blob/master/src/modbus.h#L170) as memory areas which contain the coil and register IO values.

**Comment by ocschwar** [comment]
I am writing a Modbus server implementation as my baptism into the Tokio framework. It's pretty close to done. One quick favor: if you could make binary.rs a public module I can link into it rather than plagiarize it.

**Comment by hirschenberger** [comment]
I've published a new version with your PR applied. Looking forward to your project. Perhaps we can write Unit-tests against each other.

**Comment by ocschwar** [comment]
Excellent! Thank you!

**Comment by ocschwar** [comment]
Voila: https://github.com/ocschwar/modbus-server

Primitive so far. I need to add error checking and the like.

**Comment by hirschenberger** [comment]
Ah, a Fraunhofer colleague from the US, nice to meet you.

Looks good so far but I see some redundancy to my crate. I can make more datastructures public if you name them to me or integrate your code if your implementation is more elegant. The project was a rust-learning lesson for me and has some rough edges here and there. 

Are you planning to use your code in a real project?

**Comment by ocschwar** [comment]
My pleasure!

Not using it for a project yet. I've been doing this to research using Rust for future projects. But who knows?

**Comment by flosse** [comment]
> Looks good so far but I see some redundancy to my crate. I can make more datastructures public if you name them to me or integrate your code if your implementation is more elegant.

IMHO it absolutely makes sense to share traits, structs and algorithms!

**Comment by ocschwar** [comment]
The MBAP header in tcp.rs could use sharing too. 

But at the moment I am paying a steep price for trying to use Tokio. My server will not compile because the Service trait's call() method requires a non mutable reference to self. 

So it will be next week before I have something that DTRT. (Need to remove the Service trait and run something lower level)

**Comment by ocschwar** [comment]
It runs now.

**Comment by flosse** [comment]
Hey guys, I just created an initial server implementation (on master @ [slowtec/tokio-modbus](https://github.com/slowtec/tokio-modbus)), that can be use like this:

```rust
use tokio_service::Service;
use tokio_modbus::*;

struct MbServer;

impl Service for MbServer {
    type Request = Request;
    type Response = Response;
    type Error = ::std::io::Error;
    type Future = Box<Future<Item=Self::Response, Error=Self::Error>>;

    fn call(&self, req: Self::Request) -> Self::Future {
        match req {
            Request::ReadInputRegisters(_addr, cnt) => {
                let mut registers = vec![0; cnt as usize];
                registers[2] = 0x77;
                future::ok(Response::ReadInputRegisters(registers))
            }
            _ => unimplemented!(),
        }
    }
}

let addr = "127.0.0.1:5502".parse().unwrap();
let server = Server::new_tcp(addr);
server.serve(|| Ok(MbServer));
```
There is still a lot to work on but I'd like to get some feedback from you :)
Moreover I still believe we could share some common peaces in the future.
