### ISSUE TITLE
Proposal: add support for modbus-RTU (and serial ports)

### ISSUE THREAD

**Issue by kofron** [hirschenberger/modbus-rs#25]
I'd like to contribute a module, initially modeled on the existing `tcp` module, for supporting modbus RTU communication over a serial port.  I have plenty of hardware to test and verify on, and I think this would be a really useful extension of what is already a great contribution to the ecosystem.

Is this something you'd be interested in?

**Comment by flosse** [comment]
@kofron That are great news!
At the moment I'm working at a [tokio](https://tokio.rs/)-based modbus solution that will support both clients and servers but also TCP and RTU. I didn't published it yet (you'll find it at [slowtec/tokio-modbus]( https://github.com/slowtec/tokio-modbus)) but I think we should all combine the power :) At the moment there are at least 4 intelligent heads (@hirschenberger, @kinghajj, @kofron, @flosse) that should be connected :)
My suggestion: put our code anywhere online and then let's discuss how we can share/combine/merge :)

**Comment by hirschenberger** [comment]
For me, the `modbus-rs` crate was just a hobby project for learning rust. I don't use my code in production and also don't want to invest a big amount of time to it, but I'm open for PRs and feel free to use my code for further development.

**Comment by flosse** [comment]
@hirschenberger thanks for clarification.
