### ISSUE TITLE
Transport implementing Clone

### ISSUE THREAD

**Issue by glennpierce** [hirschenberger/modbus-rs#31]
Is it possible to make Transport impl Clone ?
I want to read a lot of registers constantly without having to keep reopening a socket.
I thought it would be useful to keep the transport alive to reuse ?
Thanks

**Comment by hirschenberger** [comment]
You mean you want to read registers from multiple clones of Transport which share a common socket?

**Comment by glennpierce** [comment]
Yep. I have hundreds of devices to read with say twenty registers on each device. 

To do this in a fast way I invoke each modbus call from a different thread (locked with a mutex on ip/ port).
It would be nice not to have to reopen a socket to the device for each register but to do that would require storing the Transports 
in a structure that allows one to clone for passing to each thread.

For example

```
loop {

        let mut all_points : Vec<Point> = get_points_to_process(campus_name, requested_ip);

        let point_results: Arc<Mutex<Vec<PointResult>>> = Arc::new(Mutex::new(vec![]));
        let modbus_managers: Arc<RwLock<HashMap<SmolStr, Mutex<house_modbus::ModbusManager>>>> = Arc::new(RwLock::new(HashMap::new()));
        
        for chunk in all_points.chunks_mut(NUMBER_OF_THREADS) {

            let start = Instant::now();

            let batch_result = crossbeam::thread::scope(|s| {

                for point in chunk.iter_mut() {

      
                    let point_results_cloned = Arc::clone(&point_results);
                    let modbus_managers_cloned = Arc::clone(&modbus_managers);          // HERE ModubusManager would have to keep ref to Transport so would need to support Clone
               
                    s.spawn(move |_| {

                        let modbus_managers_map = modbus_managers_cloned.read().expect("RwLock poisoned");

                        let manager = manager_mutex_option.unwrap().lock().expect("Mutex poisoned");

                        let value_result: YosemiteResult<f64> = manager.get_value(point.order, point.data_type,
                            point.reg_type, point.register, point.scale);

                        // push result to vec point_results 
                    });

                }
            });

        };

        // process results in point_results
 }
```

The above needs Arc::clone(&modbus_managers) which would mean ModbusManager would need to keep a reference to the Transport but that then would need to be cloneable.

Perhaps there is another way to get references passed to another thread but I don't think so without unsafe code. Or perhaps the underlying socket in your code can not be cloned (I have not looked).

Thanks

**Comment by glennpierce** [comment]
Actually after having written out my earlier reply and having thought I think call all registers on each thread is a better approach anyway so will probably proceed with that.

**Comment by hirschenberger** [comment]
Yes, apart from you question, that's what I also wanted to ask. I think it's even faster to read the whole registerset at once and process  that concurrently afterwards.
