### ISSUE TITLE
404 error - documentation link in readme

### ISSUE THREAD

**Issue by delight-f** [hirschenberger/modbus-rs#39]
Documentation link in readme pointing to [https://hirschenberger.github.io/modbus-rs/modbus/index.html](url) leads to 404 error.

**Comment by hirschenberger** [comment]
Thanks for reporting, I fixed all links

**Comment by arbrauns** [comment]
I don't see where that supposedly happened? The readme still contains the exact same link, and so does Cargo.toml.

**Comment by hirschenberger** [comment]
Sorry, I only fixed the Badges and missed the Link below. Thanks for the reminder
