### ISSUE TITLE
disconnecting the client

### ISSUE THREAD

**Issue by flosse** [hirschenberger/modbus-rs#8]
At the moment the client disconnects automatically because of the implemented `Drop` trait. But if something fails, [I have no chance to catch the error](https://github.com/hirschenberger/modbus-rs/blob/master/src/tcp.rs#L214) :(
What about using a `close` method that returns a `Result` ?

**Comment by hirschenberger** [comment]
You mean the chance to catch the error of a failed shutdown of the TcpStream? Does this make sense at all? What would be the consequence in the client code?

**Comment by flosse** [comment]
> What would be the consequence in the client code?

e.g. write a message into the log file and rust continue the application. Let's say there are 100 devices that needs to be controlled. Some of them just needs to connect once an hour. Then I'd be pissed if my whole application crashes just because one connection shutdown panics!

**Comment by hirschenberger** [comment]
Yes that's correct. BTW. I don't know if the `TcpStream` disconnects automatically after a drop, so we can skip the drop impl at all.
But a `close` function would be usefull.

**Comment by flosse** [comment]
> BTW. I don't know if the `TcpStream` disconnects automatically after a drop

Yes, the example in https://doc.rust-lang.org/std/net/struct.TcpStream.html tells us that the stream closes after it runs out of scope.

**Comment by flosse** [comment]
...and here https://doc.rust-lang.org/src/std/net/tcp.rs.html#25 we have it too:

`The socket will be closed when the value is dropped.`
